baseURL = 'https://max-moment.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[server]
disableFastRender = true

pagination.pagerSize = 10
pagination.path = "page"

[params]
mainSection = ['post']
orderByDate = 'desc'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = true
      linkify = true
      strikethrough = true
      taskList = true
      table = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = true

[permalinks]
posts = '/:slug/'